#### Calculating Schmidt Coefficients for the state :$|\psi\rangle=|0\rangle(c_{0}|00\rangle+c_{1}|10\rangle)+|1\rangle(c_{2}|10\rangle+c_{3}|11\rangle)$

In [1]:
import numpy
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
import numpy
#defining a state
bitStr_arr=['000','010','110','111']
# weights=(2*numpy.random.rand(4)-1)
# weights=weights/numpy.sqrt(numpy.dot(weights,weights))
c0=0.11886944338750266
c1=-0.8601152325203439
c2=-0.34446178176855907
c3=0.356956472298864
weights=numpy.array([ c0, c1, c2, c3])
state=numpy.zeros(2**3)
indexes=numpy.array([int(bitStr_arr[i],2) for i in range(len(bitStr_arr))])
state[indexes]=weights

In [3]:
#representation of the state
numpy.set_printoptions(precision=5)
print(state)

[ 0.11887  0.      -0.86012  0.       0.       0.      -0.34446  0.35696]


In [4]:
#checking normalization
numpy.dot(weights,weights)

1.0

Representing $|\Psi\rangle$ in the tensor product of 2 subspaces, subspace-1: 1st qubit and subspace-2: 2nd and 3rd qubit<br>
$|\Psi\rangle=d_{0}|0\rangle|\phi_{0}\rangle+d_{1}|1\rangle|\phi_{1}\rangle$, where $d_{0}=\sqrt{c_{0}^{2}+c_{1}^{2}}, ~~~d_{1}=\sqrt{c_{2}^{2}+c_{3}^{2}}$<br>
<br>
$|\phi_{0}\rangle=\frac{1}{\sqrt{c_{0}^{2}+c_{1}^{2}}}\left[c_{0}|00\rangle+c_{1}|10\rangle\right]$<br>
$|\phi_{1}\rangle=\frac{1}{\sqrt{c_{2}^{2}+c_{3}^{2}}}\left[c_{2}|10\rangle+c_{3}|11\rangle\right]$

In [5]:
d0=numpy.sqrt(c0**2+c1**2)
d1=numpy.sqrt(c2**2+c3**2)
phi0=numpy.zeros(2**2)
phi1=numpy.zeros(2**2)
phi0[numpy.array([int(bitStr_arr[0][1:],2),int(bitStr_arr[1][1:],2)])]=numpy.array([c0/d0,c1/d0])
phi1[numpy.array([int(bitStr_arr[2][1:],2),int(bitStr_arr[3][1:],2)])]=numpy.array([c2/d1,c3/d1])
zero_ket=numpy.array([1,0])
one_ket=numpy.array([0,1])
state_decomp=d0*numpy.kron(zero_ket,phi0)+d1*numpy.kron(one_ket,phi1) # This should be equivalent to state

__Gram Schmidt Decomposition__<br>
$|\phi_{1,\perp}\rangle=\mathcal{N}^{-1}\left[|\phi_{1}\rangle-|\phi_{0}\rangle\langle\phi_{0}|\phi_{1}\rangle\right]$, $\langle\phi_{0}|\phi_{1,\perp}\rangle=0$

In [6]:
#Constructing two orthonormal vectors from phi0 and phi1 using Gram Schmidt decomposition
phi1_perp=phi1-numpy.dot(phi1,phi0)*phi0
Norm=numpy.sqrt(numpy.dot(phi1_perp,phi1_perp))
phi1_perp=Norm**-1*phi1_perp

In [7]:
#checking if orthogonal
print("Earlier inner product between phi0 and phi1-", numpy.dot(phi0,phi1))
print("Inner product between phi0 and phi1_perp after Gram Schmidt Decomposition-", numpy.dot(phi0,phi1_perp))

Earlier inner product between phi0 and phi1- 0.6878626691343455
Inner product between phi0 and phi1_perp after Gram Schmidt Decomposition- 1.3877787807814457e-17


Decomposing the state across two Hilbert spaces made from orthogonal vectors<br>
$|\Psi\rangle=d_{0}|0\rangle|\phi_{0}\rangle+d_{1}|1\rangle|\phi_{1}\rangle$<br>
$|\phi_{1}\rangle=\mathcal{N}|\phi_{1,\perp}\rangle+|\phi_{0}\rangle\langle\phi_{0}|\phi_{1}\rangle$<br>
$|\Psi\rangle=d_{0}|0\rangle|\phi_{0}\rangle+d_{1}\mathcal{N}|1\rangle|\phi_{1,\perp}\rangle+d_{1}|1\rangle|\phi_{0}\rangle\langle\phi_{0}|\phi_{1}\rangle$, here $\langle\phi_{1,\perp}|\phi_{0}\rangle=0$ and $\langle 1|0\rangle=0$<br>
We have accomplished the first step now, i.e. representing $|\Psi\rangle$ as ,<br>
$|\Psi\rangle=\sum_{i,j}m_{i,j}|\rho_{i}\rangle|\lambda_{j}\rangle$ where $\langle\rho_{i}|\rho_{j}\rangle=\delta_{ij}, \langle\lambda_{i}|\lambda_{j}\rangle=\delta_{ij}$ <br>
Tensor representation of the state <br>
\begin{align}
|\Psi\rangle=(|\rho_{1}\rangle ~~& ~~|\rho_{2}\rangle)\begin{pmatrix} M_{00} & M_{01} \\
                                                                   M_{10} & M_{11}
                                                    \end{pmatrix}  \begin{pmatrix}(|\lambda_{1}\rangle \\ |\lambda_{2}\rangle\end{pmatrix}
\end{align}<br>
\begin{align}M=\begin{pmatrix} M_{00} & M_{01} \\
                                                                   M_{10} & M_{11}
                \end{pmatrix}
               \end{align} 


In [10]:
M=numpy.zeros((2,2))
M[0,0]=numpy.dot(numpy.kron(zero_ket,phi0),state_decomp)
M[0,1]=numpy.dot(numpy.kron(zero_ket,phi1_perp),state_decomp)
M[1,0]=numpy.dot(numpy.kron(one_ket,phi0),state_decomp)
M[1,1]=numpy.dot(numpy.kron(one_ket,phi1_perp),state_decomp)

In [11]:
print("Tensor Representation of the 3-qubit state decomposed into two subparts of 1 and 2 qubits.")
print(M)

Tensor Representation of the 3-qubit state decomposed into two subparts of 1 and 2 qubits.
[[8.68290e-01 1.21431e-17]
 [3.41219e-01 3.60058e-01]]


Schmidt Decomposition via Singular value decomposition of above matrix <br>
https://numpy.org/doc/stable/reference/generated/numpy.linalg.svd.html<br>
$M=USV^{H}$, here $S$ is the Schmidt vector

Schmidt decomposed state<br>
$|\Psi\rangle=\lambda_{1}|\psi_{1}\rangle|\chi_{1}\rangle+\lambda_{2}|\psi_{2}\rangle|\chi_{2}\rangle$, $S=[\lambda_{1},\lambda_{2}]$, $\langle\psi_{2}|\psi_{1}\rangle=\langle\chi_{2}|\chi_{1}\rangle=0$

In [12]:
u, schmidt_coeff_vec, vh = numpy.linalg.svd(M, full_matrices=True)

In [13]:
# Schmidt Coefficient vector 
print(schmidt_coeff_vec)

[0.94351 0.33135]


In [14]:
#check Schmidt coefficients from the reduced density matrix by partial tracing one subsytem
#sqrt of the non-zero eigenvalues of the reduced density matrix are the Schmidt Cefficients.

In [15]:
import qutip
from qutip import *

In [16]:
bitStr_arr

['000', '010', '110', '111']

In [17]:
#representating |\Psi\rangle in qutip
state_qutip=weights[0]*tensor(basis(2,0),basis(2,0),basis(2,0))+weights[1]*tensor(basis(2,0),basis(2,1),basis(2,0))+weights[2]*tensor(basis(2,1),basis(2,1),basis(2,0))+weights[3]*tensor(basis(2,1),basis(2,1),basis(2,1))

In [18]:
state_qutip

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[ 0.11887]
 [ 0.     ]
 [-0.86012]
 [ 0.     ]
 [ 0.     ]
 [ 0.     ]
 [-0.34446]
 [ 0.35696]]

Constructing density matrix <br>
$\rho=|\Psi\rangle\langle\Psi|$

In [19]:
Rho=state_qutip*state_qutip.dag()

In [20]:
Rho

Quantum object: dims = [[2, 2, 2], [2, 2, 2]], shape = (8, 8), type = oper, isherm = True
Qobj data =
[[ 0.01413  0.      -0.10224  0.       0.       0.      -0.04095  0.04243]
 [ 0.       0.       0.       0.       0.       0.       0.       0.     ]
 [-0.10224  0.       0.7398   0.       0.       0.       0.29628 -0.30702]
 [ 0.       0.       0.       0.       0.       0.       0.       0.     ]
 [ 0.       0.       0.       0.       0.       0.       0.       0.     ]
 [ 0.       0.       0.       0.       0.       0.       0.       0.     ]
 [-0.04095  0.       0.29628  0.       0.       0.       0.11865 -0.12296]
 [ 0.04243  0.      -0.30702  0.       0.       0.      -0.12296  0.12742]]

Constructing reduced density matrix<br>
$\rho=Tr_{1,2}(|\Psi\rangle\langle\Psi|)$<br>
$\rho=\lambda_{1}^{2}|e_{1}\rangle\langle e_{1}|+\lambda_{2}^{2}|e_{2}\rangle\langle e_{2}|$ , here $\langle e_{1}|e_{2}\rangle=0$ and $\lambda_{1,2}$ are the Schimdt coefficients.<br>
__We will therefore verify the Schimdt coefficients obtained from svd wit that obtained from red. density matrix.__

In [21]:
red_Rho = Rho.ptrace(0)

In [22]:
w,v=numpy.linalg.eigh(red_Rho)

In [24]:
#Schmidt Coeffients are equal to square root of the red. density matrix as promised
numpy.sqrt(w)

array([0.33135, 0.94351])